fix(pandar_cloud):Fixed missing PointCloud when vibrating
tier4/HesaiLidar_General_ROS pull request #23
Opened 2024-09-05 04:28 UTC by kodamays

## Description

- hesai_driverであるhesai_pandarのpandar_pointcloudにセンサーを振動させた時に点群欠落が発生するのを防ぐ処理を追加します。

## Related links

- https://tier4.atlassian.net/browse/AEAP-1193
- https://github.com/MapIV/hesai_pandar/tree/ros2

### 変更内容
- Lidarデータパケットを1トピック分を全てPointCloudへ変換して出力するのではなく、LiDARデータパケット内でLiDARデータの終端を判定し、そこまでのデータをPointCloudへ変換して出力するするように処理を変更。
![Hesai点群欠落修正方針](https://github.com/user-attachments/assets/4739167d-29eb-4cf8-aa16-efb4595f38ec)

    - LiDARデータの終端判定処理は元々pandar_pointcloudに存在していたので、LiDARデータパケット毎にその判定処理を呼び出してLiDARデータ終端を判定し、終端に到達していた場合はそれまでのデータをPointCloudへ変換してPublishするようにしています。

## Tests performed

### 機能検証
- 修正後のhesai_driverでセンサを2分間振動させた場合に点群欠落が発生しないことが確認できています。

- 同じセンサーを用いて修正前のhesai_driverでセンサーを振動させると点群欠落が多数発生しているため、hesai_driverの修正で改善していることが確認できています。

- 修正後のhesai_driverのpandar_pointcloudから出力されるPointCloudデータの点群数(field widthの値)も振動時に点群欠落時の異常値である200点程度の値が出ないことが確認できています。
 
  [topic_echo_pointcloud.txt](https://github.com/user-attachments/files/16883874/topic_echo_pointcloud.txt)

- 修正後のhesai_pandarを使用して2時間連続して実行した場合にpandar_pointcloudからエラーや異常な警告の出力、異常終了がないことが確認できています。

  
  [pandar_launch.log](https://github.com/user-attachments/files/16883880/pandar_launch.log)

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-09-09 10:39 UTC, asa-naki requested changes

2024-09-09 10:39 UTC, asa-naki commented on pandar_pointcloud/src/pandar_cloud.cpp
> +
こちら、pre-commitなどでの、空白でしょうか？
もし不要なら削除お願いしたいです。

2024-09-09 12:04 UTC, yn-mrse requested changes

2024-09-09 12:04 UTC, yn-mrse commented on pandar_pointcloud/src/pandar_cloud.cpp
> +    if(decoder_->hasScanned()) {
early returnをお願いできますでしょうか？
あえてスコープの階層を一つ深くする理由はないと思っています。

```
if (!decoder_->hasScanned()) {
  continue;
}
```

2024-09-09 12:07 UTC, yn-mrse commented
Related Linksについてどのような関係か言及をお願いします。

2024-09-09 12:08 UTC, yn-mrse commented
> 修正後のhesai_driverでセンサを2分間振動させた場合に点群欠落が発生しないことが確認できています。

根拠となるスクリーンショットなどを添付ください。

2024-09-09 12:15 UTC, yn-mrse commented
[tier4:tier4/develop](https://github.com/tier4/hesai_pandar/tree/tier4/develop) を指定されていると思いますが、適用先はこちらのブランチであっていますでしょうか？

2024-09-09 12:28 UTC, yn-mrse commented
- 本件バグではなく仕様不具合と思われますので、タイトルをfix→featに変更ください。
- PRタイトル及びコミットメッセージは大文字利用は避けてください。

⇓下記、代案です。
feat(pandar_cloud): prevent point cloud data loss

2024-09-10 04:01 UTC, kodamays commented on pandar_pointcloud/src/pandar_cloud.cpp
> +
@asa-naki 
不要な空白でしたので削除しました。

2024-09-10 04:03 UTC, kodamays commented on pandar_pointcloud/src/pandar_cloud.cpp
> +    if(decoder_->hasScanned()) {
参考にしたコードと同じ修正にしていましたが、スコープの階層を深くする理由はなかったので提案していただいたように修正し、スコープの階層を修正しました。

2024-09-10 04:15 UTC, kodamays commented
@yn-mrse 

> Related Linksについてどのような関係か言及をお願いします。

関係性が分かりづらい状態になっていましたので、設計資料や評価資料など何に対するリンクか分かるようにし、リンク自体も設計資料や評価資料のある場所を示すよう修正しました。

> 根拠となるスクリーンショットなどを添付ください。

変化が分かるスクリーンショットと評価時の点群数が分かるログを添付しました。

> [tier4:tier4/develop](https://github.com/tier4/hesai_pandar/tree/tier4/develop) を指定されていると思いますが、適用先はこちらのブランチであっていますでしょうか？

現在eve車両で使用されているものがtier4/developの最新でしたので、三品さんに確認した上でこちらをマージ先としています。

> 本件バグではなく仕様不具合と思われますので、タイトルをfix→featに変更ください。
> PRタイトル及びコミットメッセージは大文字利用は避けてください。

了解です。タイトル名などは今後気をつけます。
代案で挙げて頂いたもので問題なさそうでしたので、そちらにタイトル名を変更しました。

2024-09-13 03:05 UTC, kodamays commented
@yn-mrse @asa-naki 
二瓶さんからslackで指摘を受けたpacketsのunpackのfor文を修正し、onProcessScan一回実施で、pointcloudが確実に1回だけpublishされるようにしました(また変化差分も小さくしております)。
この修正で問題がないか再度確認をお願いいたします。

2024-09-13 04:05 UTC, yn-mrse approved these changes
下記を確認できましたので問題ないと判断しApproveします。
- 変更概要説明が妥当であること
- 変更概要説明とソースコード上変更内容が合致すること
- テスト内容及び結果が妥当であること

リポジトリオーナーの承認後にマージいただけますと幸いです。

2024-09-13 04:31 UTC, asa-naki approved these changes
変更概要説明とソースコード上変更差分が記載内容と同一である
修正テストが問題なく行われているため、approveします

2024-09-13 07:53 UTC, 0x126 approved these changes

2024-09-13 12:39 UTC, merged