fix(pandar_cloud):fixed an issue to packet alignment
tier4/HesaiLidar_General_ROS pull request #25
Opened 2024-10-23 12:12 UTC by kodamays

## Description

- hesaiのFWでFOVを90〜270度に設定した場合にhesaiドライバーのhesai_pandarが異常終了する不具合を修正します。

## Related links

- [課題チケット](https://tier4.atlassian.net/browse/AEAP-1834)

## Tests performed

以下の対象シナリオのinputに使われるrosbagを用いてhesai_pandarの異常終了が発生しないことを確認済みです。

[Os_LSim-1-001_Night_Sunny_Flat_Headlight_Tugnova_XT32_Detection](https://evaluation.tier4.jp/evaluation/reports/125459cf-dd8c-5944-bf73-8113f0e15bdf/tests/dca7f238-16c9-5341-8531-944c42e8f580/61267e5d-f444-5175-8ddc-cd345bf97949/d17b9d9c-5b6f-5140-896d-2c8a02de29a9?project_id=odd2_reference)

[Os_LSim-1-001_Night_Sunny_Flat_Headlight_Fork_XT32_Detection](https://evaluation.tier4.jp/evaluation/reports/c7b7433f-5aa3-5866-a1ca-e9f6e59d0096/tests/7d3d0263-9109-5195-a9a0-1b7c99f7d349/4df0d8b9-24e9-5465-9cd6-ef930025f686/67563970-1299-59b0-9b84-009fd9327d05?project_id=odd2_reference)

[Os_LSim-1-001_Night_Sunny_Flat_Headlight_None_XT32_NonDetection](https://evaluation.tier4.jp/evaluation/reports/26e64897-8233-51da-bada-869846377e96/tests/cad981ac-504d-577f-8461-8e5e4b49cc0b/39552a20-2835-5e6c-8cb5-cbabb7433a7e/9d877305-d0fb-5d74-acd5-523f7db68926?project_id=odd2_reference)

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-10-23 13:29 UTC, yn-mrse requested changes

2024-10-23 13:29 UTC, yn-mrse commented on pandar_pointcloud/src/pandar_cloud.cpp
> +  bool is_hasScanned = false;
メンバ変数・ローカル変数は例外なくsnake_casesを徹底ください。

2024-10-23 13:29 UTC, yn-mrse commented on pandar_pointcloud/src/pandar_cloud.cpp
> +  if (!is_hasScanned) {
is_has_scannedという命名ではここで表現したい条件を十分に表現できていないと思いますので、
変数の命名を変更する必要があるかと思います。

2024-10-23 13:29 UTC, yn-mrse commented on pandar_pointcloud/src/pandar_cloud.cpp
> +  if (!is_hasScanned) {
ここでは
- 一度もscanの末尾に達していない
- ないし「少なくとも一回はscanの末尾に達した」条件の論理否定

になるかと思います。
短い単語表現ならば前者で、`never_detected_scan_boundary` などの表現がよいかと思います。

2024-10-24 01:06 UTC, kodamays commented on pandar_pointcloud/src/pandar_cloud.cpp
> +  bool is_hasScanned = false;
@yn-mrse 
後に挙げて頂いた指摘に合わせてnever_detected_scan_boundaryに変数名を修正しました。

2024-10-24 01:06 UTC, kodamays commented on pandar_pointcloud/src/pandar_cloud.cpp
> +  if (!is_hasScanned) {
@yn-mrse 
never_detected_scan_boundaryに変数名を修正しました。
また、変数の意味に合わせて、一度もscanの末尾に達していない場合がtrue、scanの末尾に達した場合をfalseに変更しました。

2024-10-24 08:01 UTC, sfukuta commented
@kodamays 

> hesaiのFWでFOVを90〜270度に設定した場合にhesaiドライバーのhesai_pandarが異常終了する不具合を修正します。

ソース修正内容と説明が一致してないので、修正内容と文言が一致するように変更をお願いします。
今回は、パケットの受信状況に応じて、"hasScanned"が"true"にならない事が問題ときいています。
その説明と一致していないです。

2024-10-24 08:21 UTC, kodamays commented
> @kodamays
> 
> > hesaiのFWでFOVを90〜270度に設定した場合にhesaiドライバーのhesai_pandarが異常終了する不具合を修正します。
> 
> ソース修正内容と説明が一致してないので、修正内容と文言が一致するように変更をお願いします。 今回は、パケットの受信状況に応じて、"hasScanned"が"true"にならない事が問題ときいています。 その説明と一致していないです。

@sfukuta 
descriptionを昨日の説明に合うよう修正しました。

2024-10-24 10:05 UTC, yn-mrse approved these changes

2024-10-24 10:09 UTC, merged